accounts/urls.py
from django.conf.urls import patterns, include, url
from accounts.views import *
from accounts.forms import MyPasswordResetForm

urlpatterns = patterns('',
    url(r'^login/', LogIn.as_view(), name='login'),
    url(r'^register/', RegisterUser.as_view(), name='register'),
    url(r'^logout/', LogOut, name='logout'),
    url(r'^password/reset/$',
        'django.contrib.auth.views.password_reset',
        {'post_reset_redirect' : 'done/',
         'template_name': 'accounts/password_reset_form.html',
         'email_template_name': 'accounts/password_reset_email.html',
         'password_reset_form': MyPasswordResetForm},
        name='password_reset'),
    url(r'^password/reset/done/$',
        'django.contrib.auth.views.password_reset_done',
        {'template_name': 'accounts/password_reset_done.html'}),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect' : 'accounts:login',
         'template_name': 'accounts/password_reset_confirm.html',
         'set_password_form': MySetPasswordForm},
        name='confirm'),
    url(r'^password/done/$',
        'django.contrib.auth.views.password_reset_complete'),
    url(r'^(?P<userId>\d+)/$', myaccount, name='myaccount'),
)

bowlgames/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'bowlgames.views.home', name = 'home'),
    url(r'^nfl/', include('nfl.urls', namespace = 'nfl')),
    url(r'^ncaaf/', include('ncaaf.urls', namespace = 'ncaaf')),
    url(r'^nba/', include('nba.urls', namespace = 'nba')),
    url(r'^ncaam/', include('ncaam.urls', namespace = 'ncaam')),
    url(r'^ncaaw/', include('ncaaw.urls', namespace = 'ncaaw')),
    url(r'^accounts/', include('accounts.urls', namespace = 'accounts')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^games/', include('picks.urls', namespace = "picks")),
)

urlpatterns += staticfiles_urlpatterns()

nba/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'nba.views.nbahome', name = 'nbahome'),
)

playoffs/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'playoffs.views.home', name = 'home'),
    url(r'^search$', 'playoffs.views.search', name='search'),
    url(r'^nfl/', include('nfl.urls', namespace = 'nfl')),
    url(r'^ncaaf/', include('ncaaf.urls', namespace = 'ncaaf')),
    url(r'^nba/', include('nba.urls', namespace = 'nba')),
    url(r'^ncaam/', include('ncaam.urls', namespace = 'ncaam')),
    url(r'^ncaaw/', include('ncaaw.urls', namespace = 'ncaaw')),
    url(r'^accounts/', include('accounts.urls', namespace = 'accounts')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^games/', include('picks.urls', namespace = "picks")),
)

urlpatterns += staticfiles_urlpatterns()

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from __future__ import unicode_literals
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.forms.util import ErrorList
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm


class LogInForm(forms.Form):
    """
    Form that controls log in attributes.

    """
    username = forms.CharField(label='Username', max_length=50,
        error_messages={'required': 'Enter a valid username'})
    password = forms.CharField(label='Password', widget=forms.PasswordInput,
        error_messages={'required': 'This field is required'})

    def clean_username(self):
        """
        Validate that the username exists.

        """
        existing = User.objects.filter(username__exact=self.cleaned_data['username'])
        if existing.exists():
            return self.cleaned_data['username']
        else:
            raise forms.ValidationError(_("A user with that username does not exist."))

    def __init__(self, *args, **kwargs):
        super(LogInForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['username'].widget.attrs['autofocus'] = 'autofocus'
        self.fields['password'].widget.attrs['placeholder'] = 'Password'
        self.helper = FormHelper()
        self.helper.form_id = 'id-logInForm'
        self.helper.form_class = 'crisp'
        self.helper.form_method = 'post'
        self.helper.form_action = 'login'
        self.helper.add_input(Submit('submit', 'Log-in'))

class RegistrationForm(forms.Form):
    """
    Form for registering a new user account. (Adapted from django-registration)

    Validates that the requested username is not already in use,
    that the requested email is not already in use, and
    requires the password to be entered twice to catch typos.

    """
    required_css_class = 'required'

    first_name = forms.CharField(label=_("First Name"))
    last_name = forms.CharField(label=_("Last Name"))
    username = forms.RegexField(regex=r'^[\w.@+-]+$',
                                max_length=30,
                                label=_("Username"),
                                error_messages={'invalid': _("This value may contain only letters, numbers and @/./+/-/_ characters.")})
    email = forms.EmailField(label=_("E-mail"))
    password1 = forms.CharField(widget=forms.PasswordInput,
                                label=_("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput,
                                label=_("Password (again)"),
                                error_messages={'required': _("Passwords did not match")})

    def clean(self):
        """
        Verifiy that the values entered into the two password fields
        match, and that the username and email are unique.
        Note that an error here will end up in ``non_field_errors()``
        because it doesn't apply to a single field.

        """
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(_("The two password fields didn't match."))

        if 'username' in self.cleaned_data:
            existing = User.objects.filter(username__exact=self.cleaned_data['username'])
            if existing.exists():
                self._errors['username'] = ErrorList([u"Enter a different username"])
                raise forms.ValidationError(_("A user with that username already exists."))

        if 'email' in self.cleaned_data:
            if User.objects.filter(email__iexact=self.cleaned_data['email']):
                self._errors['email'] = ErrorList([u"This email address is already in use"])
                raise forms.ValidationError(_("This email address is already in use. Please supply a different email address, or try recovering your password."))

        return self.cleaned_data

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'First Name'
        self.fields['first_name'].widget.attrs['autofocus'] = 'autofocus'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Last Name'
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Password (again)'
        self.helper = FormHelper()
        self.helper.form_id = 'id-RegistrationForm'
        self.helper.form_class = 'crisp'
        self.helper.form_method = 'post'
        self.helper.form_action = 'register'
        self.helper.add_input(Submit('submit', 'Register'))

class MyPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(MyPasswordResetForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['email'].widget.attrs['autofocus'] = 'autofocus'
        self.helper = FormHelper()
        self.helper.form_id = 'id-PasswordResetForm'
        self.helper.form_class = 'crisp'
        self.helper.form_method = 'post'
        self.helper.form_action = ''
        self.helper.add_input(Submit('submit', 'Reset'))

class MySetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(MySetPasswordForm, self).__init__(*args, **kwargs)
        self.fields['new_password1'].widget.attrs['placeholder'] = 'New Password'
        self.fields['new_password1'].widget.attrs['autofocus'] = 'autofocus'
        self.fields['new_password2'].widget.attrs['placeholder'] = 'New Password (again)'
        self.helper = FormHelper()
        self.helper.form_id = 'id-PasswordResetForm'
        self.helper.form_class = 'crisp'
        self.helper.form_method = 'post'
        self.helper.form_action = ''
        self.helper.add_input(Submit('submit', 'Change Password'))

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.generic import View
from accounts.forms import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
import re

# for functionality beyond a simple account app:
from ncaaf.models import League, LeagueUsers

class LogIn(View):
    """
    Class of functions handling user log in.

    """
    def get(self, request):
        logout(request)
        form = LogInForm()
        return render(request, 'accounts/login.html', {'form': form})

    def post(self, request):
        redirect_to = re.search(r'\?next=(.*),*', request.META.get('HTTP_REFERER', ''))
        form = LogInForm(request.POST)
        if form.is_valid():
            user = authenticate(username = form.cleaned_data['username'],
                                password = form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                if redirect_to:
                    return HttpResponseRedirect(redirect_to.group(1))
                else:
                    return HttpResponseRedirect(reverse('accounts:myaccount', kwargs={'userId':user.id}))
            else:
                error = "1"
                return render(request, 'accounts/login.html', {'form': form, 'error': error})
        else:
            if form.data['password'] == "" and form.data['username'] != "":
                form = LogInForm(form.clean)
                error = "1"
                return render(request, 'accounts/login.html', {'form': form, 'error': error})
            else:
                form = LogInForm(form.cleaned_data)
                error = "2"
                return render(request, 'accounts/login.html', {'form': form, 'error': error})

class RegisterUser(View):
    """
    Class of functions handling user registration.

    """
    def get(self, request):
        logout(request)
        form = RegistrationForm()
        return render(request, 'accounts/register.html', {'form': form})

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(username = form.cleaned_data['username'],
                                            password = form.cleaned_data['password1'],
                                            first_name = form.cleaned_data['first_name'],
                                            last_name = form.cleaned_data['last_name'],
                                            email = form.cleaned_data['email'])
            user.save()
            user_login = authenticate(username = form.cleaned_data['username'],
                                      password = form.cleaned_data['password1'])
            login(request, user_login)
            return HttpResponseRedirect(reverse('home'))
        else:
            form = RegistrationForm(form.cleaned_data)
            return render(request, 'accounts/register.html', {'form': form})

def LogOut(request):
    """
    Log out current user.

    """
    logout(request)
    return HttpResponseRedirect(reverse('home'))

def myaccount(request, userId):
    """
    Control an individuals account page, where they can view their leagues
    and edit personal information

    """
    if request.user.is_authenticated():
        # get current users leagues.
        leagues = League.objects.filter(leagueusers__userId=request.user)
        return render(request, 'accounts/myaccount.html', {'leagues': leagues})
    else:
        return HttpResponseRedirect(reverse('accounts:login'))

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <h3>Log In</h3>
  {% if error == '1' %}
    <p>Username and password did not match. Please try again. <a href ='{% url 'accounts:password_reset' %}' class='center'>Forgot Password?</a></p>
  {% elif error == '2' %}
    <p>Username does not exist. Please <a href ='{% url 'accounts:register' %}' class='center'>register</a> for a free account.</p>
  {% endif %}
  {% load crispy_forms_tags %}
  {% crispy form %}
</div>

{% endblock %}

accounts/templates/accounts/myaccount.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h2>My Account</h2>
  <div id="my-leagues">
    <h3>My Leagues</h3>
    {% if leagues %}
    {% regroup leagues by sportId as lg_list %}
      <ul>
        {% for lg in lg_list %}
          <li>{{ lg.grouper.displayName }}
            <ul>
              {% for lg2 in lg.list %}
                {% with lg.grouper.sportName|add:":leaguehome" as urltarget %}
                  <li><a href="{% url urltarget lg2.id %}">{{ lg2.leagueName }}</a> (created by {{ lg2.creator.get_full_name }})</li>
                {% endwith %}
              {% endfor %}
            </ul>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p>You are not part of any leagues at this time. To create a league, use the top navigation bar to select the sport you wish to create a league for, or search for an already created league to join.</p>
    {% endif %}
  </div>
  <br />
  <div id="account-info">
    <h3>My Account Info</h3>
    <ul>
      <li>Name: {{ user.get_full_name }}</li>
      <li>Username: {{ user.username }}</li>
      <li><a href ='{% url 'accounts:password_reset' %}' class='center'>Change Password</a></li>
    </ul>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Setting New password{% endblock %}

{% block content %}

{% if validlink %}
  <div class="container">
    {% load crispy_forms_tags %}
    {% crispy form %}
  </div>
{% else %}
<div class="container">
  <h1>Password reset unsuccessful</h1>
  <p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.</p>
  <p><a href ="{% url 'accounts:password_reset' %}" class="center">Forgot Password?</a></p>
</div>
{% endif %}

{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}

{% block title %}Password reset successful{% endblock %}

{% block content %}
<div class="container">
  <p>We've e-mailed you instructions for setting your password to the e-mail address you submitted.</p>
  <p>You should be receiving it shortly.</p>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% autoescape off %}
You're receiving this e-mail because you requested a password reset for your user account at {{ site_name }}.

Please go to the following page and choose a new password:
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:confirm' uidb64=uid token=token %}
{% endblock %}

Your username, in case you've forgotten: {{ user.username }}

Thanks for using our site!

The {{ site_name }} team.

{% endautoescape %}

accounts/templates/accounts/password_reset_form.html
{% extends "base.html" %}

{% block title %}Reset Password{% endblock %}

{% block content %}
<div class="container">
  <p>Please enter the email address associated with your account.</p>
  {% load crispy_forms_tags %}
  {% crispy form %}
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h3>Register</h3>
  {% if error %}
  <p>{{ error }}</p>
  {% endif %}
  {% load crispy_forms_tags %}
  {% crispy form %}
</div>
{% endblock %}