bowlgames/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'bowlgames.views.home', name = 'home'),
    url(r'^nfl/', include('nfl.urls', namespace = 'nfl')),
    url(r'^ncaaf/', include('ncaaf.urls', namespace = 'ncaaf')),
    url(r'^nba/', include('nba.urls', namespace = 'nba')),
    url(r'^ncaam/', include('ncaam.urls', namespace = 'ncaam')),
    url(r'^ncaaw/', include('ncaaw.urls', namespace = 'ncaaw')),
    url(r'^accounts/', include('accounts.urls', namespace = 'accounts')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^games/', include('picks.urls', namespace = "picks")),
)

urlpatterns += staticfiles_urlpatterns()

nba/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'nba.views.nbahome', name = 'nbahome'),
)

picks/urls.py
from django.conf.urls import patterns, url
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from picks import views

urlpatterns = patterns('',
    # ex: /games/
    url(r'^$', views.savepicks, name='index'),
    url(r'^yourpicks/$', views.pickwinners, name='makepicks'),
    url(r'^grid/$', views.pickgrid, name='grid'),
    url(r'^leaderboard/$', views.leader, name='leaderboard'),
)

# urlpatterns += staticfiles_urlpatterns()

playoffs/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'playoffs.views.home', name = 'home'),
    url(r'^search$', 'playoffs.views.search', name='search'),
    url(r'^nfl/', include('nfl.urls', namespace = 'nfl')),
    url(r'^ncaaf/', include('ncaaf.urls', namespace = 'ncaaf')),
    url(r'^nba/', include('nba.urls', namespace = 'nba')),
    url(r'^ncaam/', include('ncaam.urls', namespace = 'ncaam')),
    url(r'^ncaaw/', include('ncaaw.urls', namespace = 'ncaaw')),
    url(r'^accounts/', include('accounts.urls', namespace = 'accounts')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^games/', include('picks.urls', namespace = "picks")),
)

urlpatterns += staticfiles_urlpatterns()

picks/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils import timezone

# hard coded section:
currentseason = 'Conference Championships'
champgame = 'BCS CHAMPIONSHIP' # must match game title in both database and url
url = 'http://scores.espn.go.com/ncf/scoreboard?seasonYear=2014&seasonType=2&weekNumber=15'

# Code first models:
class Game(models.Model):
    game = models.CharField(max_length = 80)
    kickoff_time = models.DateTimeField()
    weight = models.IntegerField(default = 1)
    totalscore = models.IntegerField(null=True, blank=True)
    season = models.CharField(max_length = 80)
    def __unicode__(self):
        return self.game

class Team(models.Model):
    game = models.ForeignKey(Game)
    team = models.CharField(max_length = 80)
    # win = models.NullBooleanField()
    win = models.IntegerField(default = 0)
    display_name = models.CharField(max_length = 2)
    def __unicode__(self):
        return self.team

class UserPicks(models.Model):
    user = models.ForeignKey(User)
    game = models.ForeignKey(Game)
    pick = models.ForeignKey(Team, null=True, blank=True)
    tiebreak = models.IntegerField(null=True, blank=True)
    pick_date = models.DateTimeField(null=True, blank=True)

picks/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.contrib.auth import authenticate
from django.db.models import Sum
import datetime
import re
from django.utils import timezone
from ranking import Ranking

from django.contrib.auth.models import User
from picks.models import *

def pickwinners(request):
    """Renders the pick selection page. Populates dropdown lists"""
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('accounts:login'))
    # Close picks after first kickoff
    # if min(Game.objects.filter(season = currentseason)\
    #     .values_list('kickoff_time', flat=True)) < timezone.now():
    #     msg1 = "Too Late!"
    #     msg2 = "The first game has already started. You may no longer change your picks, but you may check them "
    #     return render(request, 'picks/closed.html', {'msg_head': msg1, 'msg_body': msg2})
    else:
        game_list = Game.objects.filter(season=currentseason)
        user_ob = request.user
        context = {'game_list': game_list, 'user_ob': user_ob}
        return render(request, 'picks/gamepicks.html', context)

def savepicks(request):
    """Saves picks from pick selection page. Renders current picks page"""
    def isInt(num):
        try:
            int(num)
        except ValueError:
            return False
        else:
            if int(num) > 0:
                return True
            else:
                return False

    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('accounts:login'))
    else:
        user = request.user
        game_list = Game.objects.filter(season = currentseason).values_list('id', flat=True)
        key_list = list(set(request.POST) & set(map(str, game_list)))
        tiebreak_error = False

        for key in key_list:
            pick_exists = UserPicks.objects.filter(
                          user = User.objects.filter(username=user),
                          game = key)

            tiebreaker_pick = request.POST.get(key + '_tiebreak', None)

            if tiebreaker_pick in [None, '']:
                if(pick_exists):
                    if(request.POST[key] == ''):
                        continue
                    else:
                        pick_exists.update(pick = Team.objects.get(id = request.POST[key]),
                                           pick_date = timezone.now())
                else: # if pick does not exist
                    if(request.POST[key] == ''):
                        up = UserPicks(user = User.objects.get(username = user),
                                       game = Game.objects.get(id = key))
                        up.save()
                    else:
                        up = UserPicks(user = User.objects.get(username = user),
                                       game = Game.objects.get(id = key),
                                       pick = Team.objects.get(id = request.POST[key]),
                                       pick_date = timezone.now())
                        up.save()
            else: # tiebreaker pick is not None or '' (blank)
                if isInt(tiebreaker_pick) is False:
                    tiebreak_error = True
                    break
                else:
                    if(pick_exists):
                        if(request.POST[key] == ''):
                            pick_exists.update(tiebreak = int(tiebreaker_pick),
                                               pick_date = timezone.now())
                        else:
                            pick_exists.update(pick = Team.objects.get(id = request.POST[key]),
                                               tiebreak = int(tiebreaker_pick),
                                               pick_date = timezone.now())
                    else: # if pick does not exist
                        if(request.POST[key] == ''):
                            up = UserPicks(user = User.objects.get(username = user),
                                           tiebreak = int(tiebreaker_pick),
                                           game = Game.objects.get(id = key))
                            up.save()
                        else:
                            up = UserPicks(user = User.objects.get(username = user),
                                           game = Game.objects.get(id = key),
                                           pick = Team.objects.get(id = request.POST[key]),
                                           tiebreak = int(tiebreaker_pick),
                                           pick_date = timezone.now())
                            up.save()

        if tiebreak_error:
            game_list = Game.objects.filter(season=currentseason)
            user_ob = request.user
            error_message = 'Your tiebreaker points (' + tiebreaker_pick + ') must be a positive whole number'
            context = {'game_list': game_list, 'user_ob': user_ob, 'error_message': error_message}
            return render(request, 'picks/gamepicks.html', context)
        else:
            allpicks = UserPicks.objects.filter(user = User.objects.filter(username=user),
                                                game__season = currentseason)
            context = {'allpicks': allpicks}  # 'out_list': key_list,
            return render(request, 'picks/output.html', context)

def pickgrid(request):
    """Renders the grid of all picks by all users"""
    # Close grid while picks are live (before first kickoff)
    # if min(Game.objects.filter(season = currentseason)\
        # .values_list('kickoff_time', flat=True)) > timezone.now():
        # msg1 = "No Peeking!"
        # msg2 = "Others are still making their picks. You may check your picks "
        # return render(request, 'picks/closed.html', {'msg_head': msg1, 'msg_body': msg2})
    # else:
    users = User.objects.filter(id__in=UserPicks.objects.filter(game__season = currentseason)\
        .values('user').distinct())
    games = Game.objects.filter(season = currentseason)
    allpicks = UserPicks.objects.filter(game__season = currentseason)
    allpicks2 = UserPicks.objects.filter(game__season = currentseason).order_by('game')
    pointlist = User.objects.filter(userpicks__game__season = currentseason)\
        .annotate(points=Sum('userpicks__pick__win'))

    for person in pointlist:
        if person.points == None:
            person.points = 0

    context = {'users': users, 'games': games, 'allpicks': allpicks,
               'allpicks2': allpicks2, 'pointlist': pointlist}
    return render(request, 'picks/pickgrid.html', context)

def leader(request):
    """Renders the leaderboard for all users"""
    currentuser = request.user
    pointlist = User.objects.filter(userpicks__game__season = currentseason)\
        .annotate(points=Sum('userpicks__pick__win'))\
        .order_by('-points', 'first_name')

    for person in pointlist:
        if person.points == None:
            person.points = 0

    def getPoints(self):
        return self.points
    def breakTie(self):
        return (abs(self.userpicks_set.get(game__game__contains = champgame).tiebreak - true_score),
                self)
    def getBreakTie(self):
        return breakTie(self)[0]

    true_score = Game.objects.get(game__contains=champgame).totalscore
    if true_score is None:
        ranks = Ranking(pointlist, start = 1, key = getPoints)
        ranklist = list(ranks)
        winner = False
    else:
        ranks = Ranking(pointlist, start = 1, key = getPoints)
        ranklist = list(ranks)

        firstplacelist = [x for (rank, x) in ranklist if rank == 1]

        firstplaceranks = [breakTie(x) for x in firstplacelist]
        firstplaceranks.sort()
        firstplace = firstplaceranks[0]
        pointlist2 = User.objects.filter(userpicks__game__season = currentseason)\
            .exclude(id = firstplace[1].id)\
            .annotate(points=Sum('userpicks__pick__win'))\
            .order_by('-points', 'first_name')
        for person in pointlist2:
            if person.points == None:
                person.points = 0
        therest = Ranking(pointlist2, start = 2, key = getPoints)
        ranklist = list(therest)
        ranklist.insert(0, (1, firstplace[1]))
        winner = firstplace[1].first_name


    context = {'pointlist': ranklist, 'currentuser': currentuser, 'winner': winner}
    return render(request, 'picks/leaderboard.html', context)

picks/templates/picks/closed.html
{% extends "base.html" %}

{% block content %}

<div class="container">
  <h2>{{ msg_head }}</h2>
  <p>{{ msg_body }}<a href="{% url 'picks:index' %}">here</a>.</p>
</div>

{% endblock %}

picks/templates/picks/gamelist.html
{% extends "base.html" %}

{% block content %}
{% if game_list %}
    <ul>
    {% for game in game_list %}
        <li>{{ game.game }}; Kickoff: {{ game.kickoff_time }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No games are available.</p>
{% endif %}
{% endblock %}

picks/templates/picks/gamepicks.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <h2>Game Picker</h2>

    {% if error_message %}
    <p><strong><font color="red">{{ error_message }}</font></strong></p>
    {% endif %}

    {% if game_list %}
	    <form action="{% url 'picks:index' %}" method="post" role="form">
	    {% csrf_token %}
        {% for bowl in game_list|dictsort:"kickoff_time" %}
            <div class="form-group">
	            <label for="game">{{ bowl.game }}</label>
		        <select name="{{ bowl.id }}" class="form-control">
			        <option value="">Choose Team for {{ bowl.game }}</option>
                {% for teams in bowl.team_set.all %}
			        <option value = "{{ teams.id }}">{{ teams.team }}</option>
		        {% endfor %}
		        </select>
	            {% if 'BCS' in bowl.game %}
	            <input name="{{ bowl.id }}_tiebreak" class="form-control" placeholder="{{ bowl.game }} Total Points">
		        {% endif %}
		    </div>
        {% endfor %}
	    <button type="submit" class="btn btn-default">Submit Picks</button>
	    </form>
    {% else %}
        <p>No games are available<p>
    {% endif %}
</div>

{% endblock %}

picks/templates/picks/index.html
{% extends "base.html" %}

{% block content %}
{% if game_list %}
    <ul>
    {% for game in game_list %}
        <li>{{ game.game }}; Kickoff: {{ game.kickoff_time }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No games are available.</p>
{% endif %}
{% endblock %}

picks/templates/picks/leaderboard.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<h2>Leaderboard</h2>
	{% if winner %}
		<h3>Congratulations 2014 Champion: {{ winner }}!</h3>
	{% endif %}
	<div class="panel panel-default">
		<table class="table table-hover table-condensed">
			<thead>
				<th>Rank</th>
				<th>Player</th>
				<th>Points</th>
			</thead>
			<tbody>
			{% for ranklist in pointlist %}
				<tr class="{% if ranklist.1 == currentuser %}info{% else %}{% endif %}">
					<th class="rank">{{ ranklist.0 }}</th>
					<th class="player">{{ ranklist.1.first_name }}</th>
					<td class="points">{{ ranklist.1.points }}</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>
</div>
{% endblock %}

picks/templates/picks/output.html
{% extends "base.html" %}

{% block content %}

<div class="container">
	<h2>My Picks</h2>
	{% if allpicks %}
		<table class="table">
			<tr>
				<th>Game</th>
				<th>Your Pick</th>
				<th>Pick Date</th>
			</tr>
			{% for item in allpicks|dictsort:"game.kickoff_time" %}
			<tr>
				<td>{{ item.game }}</td>
				<td>{{ item.pick }}</td>
				<td>{{ item.pick_date }}</td>
			</tr>
			{% if 'BCS' in item.game.game %}
			<tr>
				<td>{{ item.game }} Tiebreaker</td>
				<td>{{ item.tiebreak }} total points</td>
				<td>{{ item.pick_date }}</td>
			</tr>
			{% endif %}
			{% endfor %}
		</table>
	{% else %}
		<p>You have not made any picks yet!<p>
		{% for x in posted %}
		<li>{{ x }}</li>
		{% endfor %}
	{% endif %}
	<a href="{% url 'picks:makepicks' %}">Make or change your picks</a>
</div>

{% endblock %}

picks/templates/picks/pickgrid.html
{% extends "base.html" %}

{% block css %}
	td.winner { background-color: yellow !important }
{% endblock %}

{% block content %}
<div class="container">
	<h2>Picks Grid</h2>

	{% regroup allpicks2 by game as game_list %}
	<table class="table table-bordered table-hover table-condensed">
		<thead>
			<tr>
				<th>Game</th>
				{% for u in users %}
				<th>{{ u.first_name }}</th>
				{% endfor %}
			</tr>
		</thead>
		<tbody>
		{% for g in game_list|dictsort:"grouper.kickoff_time" %}
			<tr>
				<th title="{{ g.grouper.team_set.first }} vs. {{ g.grouper.team_set.last }}: {{ g.grouper.kickoff_time }}" data-container="body" data-toggle="tooltip" data-placement="bottom"><span>{{ g.grouper }}</span></th>
				{% for item in g.list %}
					{% if item.pick.win %}
						<td title="{{ item.pick }}" class="winner success" data-container="body" data-toggle="tooltip" data-placement="bottom">{{ item.pick.display_name }}</td>
					{% else %}
						<td title="{{ item.pick }}" class="loser" data-container="body" data-toggle="tooltip" data-placement="bottom">{{ item.pick.display_name }}</td>
					{% endif %}
				{% endfor %}
			</tr>
			{% if 'BCS' in g.grouper.game %}
			<tr>
				<th><span>BCS Tiebreaker</span></th>
				{% for item in g.list %}
				<td>{{ item.tiebreak }}</td>
				{% endfor %}
			</tr>
			{% endif %}
		{% endfor %}
			<tr>
				<th>Points:</th>
				{% for x in pointlist %}
				<th>{{ x.points }}</th>
				{% endfor %}
			</tr>
		</tbody>
	</table>
</div>
{% endblock %}

picks/templates/picks/pickgrid_old.html
{% extends "base.html" %}

{% block css %}
	td.winner { background-color: yellow }
{% endblock %}

{% block content %}

<h2>Game Picker</h2>
<p>Please review your picks below:</p>

{% regroup allpicks by user as user_list %}
<table>
	<tr>
		<th>Game</th>
		{% for g in games %}
		<th>{{ g.game }}</th>
		{% endfor %}
	</tr>
	{% for u in user_list %}
	<tr>
	    <th>{{ u.grouper.first_name }}</th>
	    {% for item in u.list %}
		<td>{{ item.pick.display_name }}</td>
		{% endfor %}
	</tr>
	{% endfor %}
</table>

<br />

<ul>
{% for user in user_list %}
    <li>{{ user.grouper }}
    <ul>
        {% for item in user.list %}
          <li>{{ item.game }}: {{ item.pick }}</li>
        {% endfor %}
    </ul>
    </li>
{% endfor %}
</ul>

<br />

{% regroup allpicks2 by game as game_list %}
<table>
	<tr>
		<th>Game</th>
		{% for u in users %}
		<th>{{ u.first_name }}</th>
		{% endfor %}
	</tr>
	{% for g in game_list %}
	<tr>
	    <th><span>{{ g.grouper }}</span></th>
	    {% for item in g.list %}
			{% if item.pick.win %}
				<td class="winner">{{ item.pick.display_name }}</td>
			{% else %}
				<td class="loser">{{ item.pick.display_name }}</td>
			{% endif %}
		{% endfor %}
	</tr>
	{% endfor %}
</table>

<ul>
{% for game in game_list %}
    <li>{{ game.grouper }}
    <ul>
        {% for item in game.list %}
          <li>{{ item.user }}: {{ item.pick }}</li>
        {% endfor %}
    </ul>
    </li>
{% endfor %}
</ul>

{% endblock %}