bowlgames/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'bowlgames.views.home', name = 'home'),
    url(r'^nfl/', include('nfl.urls', namespace = 'nfl')),
    url(r'^ncaaf/', include('ncaaf.urls', namespace = 'ncaaf')),
    url(r'^nba/', include('nba.urls', namespace = 'nba')),
    url(r'^ncaam/', include('ncaam.urls', namespace = 'ncaam')),
    url(r'^ncaaw/', include('ncaaw.urls', namespace = 'ncaaw')),
    url(r'^accounts/', include('accounts.urls', namespace = 'accounts')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^games/', include('picks.urls', namespace = "picks")),
)

urlpatterns += staticfiles_urlpatterns()

nba/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'nba.views.nbahome', name = 'nbahome'),
)

ncaaf/urls.py
from django.conf.urls import patterns, include, url
from ncaaf.views import *

urlpatterns = patterns('',
    url(r'^$', ncaafHome.as_view(), name = 'ncaafhome'),
    url(r'^(?P<leagueId>\d+)/$', leaguehome, name='leaguehome'),
    url(r'^(?P<leagueId>\d+)/join$', leaguejoin.as_view(), name='leaguejoin'),
)

ncaam/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'ncaam.views.ncaamhome', name = 'ncaamhome'),
)

ncaaw/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'ncaaw.views.ncaawhome', name = 'ncaawhome'),
)

nfl/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'nfl.views.nflhome', name = 'nflhome'),
)

playoffs/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'playoffs.views.home', name = 'home'),
    url(r'^search$', 'playoffs.views.search', name='search'),
    url(r'^nfl/', include('nfl.urls', namespace = 'nfl')),
    url(r'^ncaaf/', include('ncaaf.urls', namespace = 'ncaaf')),
    url(r'^nba/', include('nba.urls', namespace = 'nba')),
    url(r'^ncaam/', include('ncaam.urls', namespace = 'ncaam')),
    url(r'^ncaaw/', include('ncaaw.urls', namespace = 'ncaaw')),
    url(r'^accounts/', include('accounts.urls', namespace = 'accounts')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^games/', include('picks.urls', namespace = "picks")),
)

urlpatterns += staticfiles_urlpatterns()

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <link href="{% static 'site.css' %}" rel="stylesheet">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" ></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

  <title>{% block title %}Playoff Champions{% endblock %}</title>

	<style>{% block css %}{% endblock %}</style>
  </head>

  <body>
  	<nav class="navbar navbar-default">
  		<div class="container-fluid">
  			<div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
  				<a class="navbar-brand" href="{% url 'home' %}">Playoff Champions</a>
  			</div>
  			<div class="collapse navbar-collapse">
  				<ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Football <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'nfl:nflhome' %}">NFL</a></li>
                <li><a href="{% url 'ncaaf:ncaafhome' %}">NCAA</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Basketball <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'nba:nbahome' %}">NBA</a></li>
                <li><a href="{% url 'ncaam:ncaamhome' %}">NCAA Men</a></li>
                <li><a href="{% url 'ncaaw:ncaawhome' %}">NCAA Women</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Baseball <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">MLB</a></li>
                <li><a href="#">NCAA</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Soccer <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">World Cup</a></li>
                <li><a href="#">MLS</a></li>
              </ul>
            </li>
  				</ul>
    			<ul class="nav navbar-nav navbar-right">
            <li>
              <form class="navbar-form navbar-left nav-links" role="search" method="get" action="{% url 'search' %}">
                <div class="input-group">
                  <input type="text" name="q" id="id_q" class="form-control input-xs" placeholder="Search for a League" />
                  <span class="input-group-btn">
                    <button type="submit" class="btn btn-xs btn-warning"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                  </span>
                </div>
              </form>
      				{% if user.is_active %}
      				<p class="navbar-text">Welcome back, <strong>{% firstof user.get_short_name user.get_username %}</strong>!
                <div class="btn-group btn-group-xs nav-links" role="group" aria-label="...">
                  <a href="{% url 'accounts:myaccount' user.id %}" class="btn btn-warning" role="button">My Leagues</a>
                  <a href="{% url 'accounts:logout' %}" class="btn btn-warning" role="button">Log out</a>
                </div>
      				{% else %}
      				<p class="navbar-text">Welcome, Guest!
                <div class="btn-group btn-group-xs nav-links" role="group" aria-label="...">
                  <a href="{% url 'accounts:login' %}" class="btn btn-warning" role="button">Log In</a>
                  <a href="{% url 'accounts:register' %}" class="btn btn-warning" role="button">Register</a>
                </div>
      				{% endif %}
            </li>
          </ul>
  			</div>
  		</div>
  	</nav>


    {% block content %}{% endblock %}

    <hr>
    <!--<div class="container">
      <p>Dedicated to Nancy Lee - Last updated 2014-12-10</p>
    </div>-->
  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<div id="homejumbo" class="jumbotron">
		<h2>Welcome to Playoff Champions!</h2>
	</div>
	<div class="container">
		<p>Here at Playoff Champions, we strive to be your go to site for social sports pools. We are not a gambling site, we are a pool management site. Create a league, invite friends or coworkers, and use our site to easily track your progress online and on your mobile device. We'll do the hard work and let you enjoy the games (and yes, the occasional bet).</p>
	</div>
</div>
{% endblock %}

templates/searchresults.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <p>Thanks for searching for: "{{ query_string }}"</p>
  {% if found_ids %}
    {% regroup found_ids by sportId as id_result %}
    <p>Your search matched exactly to the id for:</p>
    <ul>
      {% for i in id_result %}
        <li>{{ i.grouper.displayName }}
          <ul>
            {% for i2 in i.list %}
              {% with i.grouper.sportName|add:":leaguejoin" as urltargetjoin and i.grouper.sportName|add:":leaguehome" as urltargetview %}
                <li class="custom-list">
                  <div>
                    {% if i2 in user_leagues %}
                    <a href="{% url urltargetview i2.id %}"><button class="btn btn-xs btn-warning btn-list">View</button></a>
                    {% else %}
                    <a href="{% url urltargetjoin i2.id %}"><button class="btn btn-xs btn-primary btn-list">Join</button></a>
                    {% endif %}
                    {{ i2.leagueName }} (created by {{ i2.creator.get_full_name }})
                    {% if i2.isPrivate %}
                    <span class="glyphicon glyphicon-lock" aria-label="Private" title="Private"></span>
                    {% endif %}
                  </div>
                </li>
              {% endwith %}
            {% endfor %}
          </ul>
        </li>
      {% endfor %}
    </ul>
  {% endif %}
  {% if found_entries %}
  <p>Below are the leagues that match this name</p>
  {% regroup found_entries by sportId as results %}
  <ul>
    {% for r in results %}
    <li>{{ r.grouper.displayName }}
      <ul>
        {% for r2 in r.list %}
        {% with r.grouper.sportName|add:":leaguejoin" as urltargetjoin and r.grouper.sportName|add:":leaguehome" as urltargetview %}
        <li class="custom-list">
          <div>
            {% if r2 in user_leagues %}
              <a href="{% url urltargetview r2.id %}"><button class="btn btn-xs btn-warning btn-list">View</button></a>
            {% else %}
              <a href="{% url urltargetjoin r2.id %}"><button class="btn btn-xs btn-primary btn-list">Join</button></a>
            {% endif %}
            {{ r2.leagueName }} (created by {{ r2.creator.get_full_name }})
            {% if r2.isPrivate %}
              <span class="glyphicon glyphicon-lock" aria-label="Private" title="Private"></span>
            {% endif %}
          </div>
        </li>
        {% endwith %}
        {% endfor %}
      </ul>
    </li>
    {% endfor %}
  </ul>
  {% endif %}
  {% if found_ids == None and found_entries == None %}
    <p>Unfortunately, there are no leagues that match this name</p>
  {% endif %}
</div>

<script type="text/javascript">
  function joinLeague(node) {
    return confirm("Are you sure you wish to join this league?");
  }
</script>
{% endblock %}